'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { modules, lessonIds } from '../curriculum';
import { capstone, finalProjectStages, moduleTasks } from '../tasks-data';

export default function TaskWorkspace() {
  const [completed,setCompleted]=useState<Set<string>>(new Set());
  useEffect(()=>{fetch('/api/progress').then(r=>r.ok?r.json():{completed:[]}).then(data=>setCompleted(new Set(data.completed??[])));},[]);
  const allDone=lessonIds.every(id=>completed.has(id));
  return <main className="tasks-page"><header><span className="kicker">Practice studio</span><h1>Learn it. Then build it.</h1><p>Each project unlocks when its module is complete. No videos—just a real brief, clear deliverables and a starter pattern.</p></header><div className="tasks-list">{modules.map(module=>{const unlocked=module.lessons.every(lesson=>completed.has(lesson.id));const task=moduleTasks[module.id];return <article id={module.id} className={unlocked?'task-card unlocked':'task-card locked'} key={module.id}><div className="task-index">{module.number}</div><div className="task-main"><span className="task-status">{unlocked?'Unlocked':'Complete learning to unlock'}</span><h2>{task.title}</h2><p>{task.brief}</p><h3>Deliverables</h3><ul>{task.deliverables.map(item=><li key={item}>{item}</li>)}</ul>{unlocked&&<pre><code>{task.starter}</code></pre>}</div><div className="task-side">{unlocked?<><strong>Ready to build</strong><button>Start task →</button></>:<><strong>{module.lessons.filter(lesson=>completed.has(lesson.id)).length}/{module.lessons.length}</strong><span>lessons complete</span><Link href={`/learn?lesson=${module.lessons.find(lesson=>!completed.has(lesson.id))?.id??module.lessons[0].id}`}>Continue learning</Link></>}</div></article>})}</div><section id="final-project" className={allDone?'capstone unlocked':'capstone'}><div className="capstone-heading"><div><span className="kicker">Final guided project</span><h2>{capstone.title}</h2></div><a className="dataset-download" href="/downloads/learnflow_customer_churn_practice.xlsx" download>Download sample workbook <span>↓</span></a></div><p>{capstone.brief}</p><div className="dataset-facts"><span><strong>300</strong> customer rows</span><span><strong>18</strong> useful columns</span><span><strong>4</strong> guided sheets</span><span><strong>10</strong> project stages</span></div><h3 className="project-stages-title">One task for every topic</h3><div className="project-stages">{finalProjectStages.map(stage=><article key={stage.number}><b>{String(stage.number).padStart(2,'0')}</b><div><h3>{stage.title}</h3><p>{stage.task}</p></div></article>)}</div><h3 className="final-deliverables-title">Final submission</h3><ul>{capstone.deliverables.map(item=><li key={item}>{item}</li>)}</ul><strong>{allDone?'Your complete project is unlocked. Start with the Project Guide sheet.':'You may preview the workbook now. Complete every lesson before starting the final submission.'}</strong></section></main>;
}
