export type Lesson = {
  id: string; title: string; minutes: number; explanation: string; example: string;
  exercise: { question: string; choices: string[]; answer: number; feedback: string };
};
export type Module = { id:string; number:string; title:string; subtitle:string; color:string; symbol:string; lessons:Lesson[] };
const lesson = (id:string,title:string,minutes:number,explanation:string,example:string,question:string,choices:string[],answer:number,feedback:string):Lesson => ({id,title,minutes,explanation,example,exercise:{question,choices,answer,feedback}});

export const modules: Module[] = [
  { id:'data', number:'01', title:'Data foundations', subtitle:'NumPy, Pandas & visualisation', color:'sun', symbol:'▦', lessons:[
    lesson('numpy-arrays','NumPy arrays',12,'Arrays store values of one type and make numerical operations fast. Shape describes their dimensions; indexing selects individual values or slices.','x = np.array([2, 4, 6])\nx.mean()  # 4.0','Which expression selects the first item in x?',['x[0]','x[1]','x.first()'],0,'Python uses zero-based indexing, so the first position is 0.'),
    lesson('pandas-frames','Pandas DataFrames',15,'A DataFrame is a labelled table. Columns are features and rows are observations. Use head(), info() and describe() to understand a new dataset.','df = pd.read_csv("sales.csv")\ndf.head()','Which method reveals column types and missing counts?',['df.plot()','df.info()','df.sample()'],1,'info() summarizes columns, data types and non-null counts.'),
    lesson('clean-data','Cleaning data',14,'Clean data before modelling: remove duplicates, correct types and decide how to handle missing values. Never hide these decisions.','df["age"] = df["age"].fillna(df["age"].median())','What is a sensible fill value for skewed numeric data?',['The median','A random word','Always zero'],0,'The median is robust to unusually large or small values.'),
    lesson('categoricals','Categorical variables',13,'Models need numbers. One-hot encoding creates a binary column for each unordered category; ordinal encoding is for ordered categories.','pd.get_dummies(df, columns=["city"])','Which encoding fits red, green and blue?',['One-hot encoding','Date encoding','Min-max scaling'],0,'Colours have no natural order, so one-hot encoding is appropriate.'),
  ]},
  { id:'stats', number:'02', title:'Statistics for ML', subtitle:'Probability, distributions & testing', color:'mint', symbol:'⌁', lessons:[
    lesson('center-spread','Centre and spread',14,'Mean and median describe centre. Variance and standard deviation describe spread. Compare both when distributions contain outliers.','values.mean()\nvalues.std()','Which measure is least affected by one extreme outlier?',['Mean','Median','Variance'],1,'The median depends on rank, not the magnitude of the extreme value.'),
    lesson('distributions','Distributions',16,'A distribution describes possible values and their frequency. Normal distributions are symmetric; real data may be skewed or multi-modal.','sns.histplot(df["income"], kde=True)','A long right tail indicates what?',['Right skew','Perfect normality','No variation'],0,'A few high values stretch the distribution to the right.'),
    lesson('correlation','Correlation',12,'Correlation measures linear association, not causation. Values near +1 or -1 indicate strong linear relationships; near 0 means weak linear association.','df.corr(numeric_only=True)','If r = -0.9, the variables have…',['A strong negative relationship','No relationship','A strong positive relationship'],0,'As one variable rises, the other tends to fall strongly.'),
    lesson('hypothesis','Hypothesis testing',18,'A hypothesis test asks whether evidence is inconsistent with a null hypothesis. A p-value is not the probability that the null is true.','stats.ttest_ind(group_a, group_b)','With α=.05 and p=.02, what is the usual decision?',['Reject the null','Prove the null','Increase p manually'],0,'Because p is below α, the data is considered inconsistent with the null.'),
  ]},
  { id:'core', number:'03', title:'Core machine learning', subtitle:'Train, validate and generalise', color:'blue', symbol:'⌘', lessons:[
    lesson('problem-types','Regression vs classification',11,'Regression predicts a continuous value. Classification predicts a category or class probability.','price → regression\nspam/not spam → classification','Predicting house price is…',['Regression','Classification','Clustering'],0,'Price is a continuous numeric target.'),
    lesson('train-test','Train/test split',13,'Fit the model on training data and reserve test data for a final unbiased check. Split before learning preprocessing parameters.','train_test_split(X, y, test_size=.2, random_state=42)','Why keep a test set?',['Estimate performance on unseen data','Make training slower','Store missing values'],0,'The test set simulates future examples the model did not train on.'),
    lesson('fit-balance','Overfitting & underfitting',14,'An underfit model is too simple for the pattern. An overfit model memorises training noise and performs poorly on new data.','high train score + low test score → overfit','Which pattern suggests overfitting?',['95% train, 62% test','60% train, 60% test','95% train, 94% test'],0,'The large generalisation gap is the key warning sign.'),
    lesson('cross-validation','Cross-validation',16,'K-fold cross-validation rotates the validation fold, producing a more stable performance estimate and revealing variability.','cross_val_score(model, X, y, cv=5)','In 5-fold CV, how many validation rounds run?',['1','5','10'],1,'Every fold acts as validation data once.'),
  ]},
  { id:'algorithms', number:'04', title:'ML algorithms', subtitle:'From linear models to boosting', color:'rose', symbol:'⤴', lessons:[
    lesson('linear-logistic','Linear & logistic regression',17,'Linear regression predicts numbers with a weighted sum. Logistic regression maps a weighted sum to a class probability.','LogisticRegression().fit(X_train, y_train)','Which model predicts a yes/no outcome?',['Linear regression','Logistic regression','PCA'],1,'Logistic regression is a classification algorithm despite its name.'),
    lesson('trees-forests','Trees & random forests',18,'Decision trees make readable splits. Random forests average many varied trees, reducing variance and usually improving generalisation.','RandomForestClassifier(n_estimators=200)','Why use many trees?',['Reduce variance','Remove the target','Guarantee perfection'],0,'Averaging decorrelated trees creates a more stable model.'),
    lesson('knn-svm','KNN & SVM',18,'KNN predicts from nearby training examples. SVM finds a boundary with maximum margin and benefits strongly from scaled features.','make_pipeline(StandardScaler(), SVC())','Which step is especially important for SVM?',['Feature scaling','Alphabetical sorting','Dropping all labels'],0,'Large-scale features can otherwise dominate distances and margins.'),
    lesson('boosting','Gradient boosting',18,'Boosting builds weak learners sequentially, with each new tree correcting previous errors. Learning rate and tree count work together.','XGBClassifier(n_estimators=300, learning_rate=.05)','Boosting trees are built…',['Sequentially','As one giant tree','Without errors'],0,'Each learner focuses on what the current ensemble gets wrong.'),
  ]},
  { id:'evaluation', number:'05', title:'Model evaluation', subtitle:'Use the metric that matches the goal', color:'violet', symbol:'◎', lessons:[
    lesson('regression-metrics','Regression metrics',15,'MAE is easy to interpret, MSE/RMSE penalise large misses, and R² compares performance with predicting the mean.','mean_absolute_error(y_test, pred)','Which metric stays in the target unit and is robust?',['MAE','MSE','Accuracy'],0,'MAE is the average absolute error in the original target unit.'),
    lesson('classification-metrics','Precision, recall & F1',16,'Precision asks how many positive predictions were correct. Recall asks how many real positives were found. F1 balances both.','classification_report(y_test, pred)','For disease screening, which often matters most?',['Recall','R²','MAE'],0,'High recall reduces the number of missed positive cases.'),
    lesson('roc-confusion','Confusion matrix & ROC-AUC',16,'A confusion matrix counts prediction outcomes. ROC-AUC measures ranking quality across classification thresholds.','ConfusionMatrixDisplay.from_predictions(y, pred)','A false positive means…',['Predicted yes, actually no','Predicted no, actually yes','Predicted correctly'],0,'The model raised a positive signal for a negative case.'),
  ]},
  { id:'pipelines', number:'06', title:'Features & pipelines', subtitle:'Reliable preprocessing and tuning', color:'orange', symbol:'⇄', lessons:[
    lesson('scaling-encoding','Scaling & encoding',16,'Scale numeric features and encode categorical ones. Learn every transformation only from training data to prevent leakage.','ColumnTransformer([("num", StandardScaler(), nums)])','When should a scaler learn mean and std?',['Training data only','Full dataset before splitting','Test data only'],0,'Using test statistics leaks information into training.'),
    lesson('pipeline','ColumnTransformer & Pipeline',17,'A Pipeline chains preprocessing and modelling so the same fitted steps run during validation, testing and prediction.','Pipeline([("prep", prep), ("model", model)])','What key problem does a pipeline reduce?',['Data leakage','Disk space','Class names'],0,'Pipelines keep preprocessing inside each training fold.'),
    lesson('tuning','Hyperparameter tuning',18,'Grid or random search tests configurations using cross-validation. Tune on validation folds, then evaluate once on untouched test data.','RandomizedSearchCV(pipe, params, cv=5)','What data should choose hyperparameters?',['Validation folds','Final test set','Future production labels'],0,'The final test set must remain an unbiased last check.'),
  ]},
  { id:'unsupervised', number:'07', title:'Unsupervised ML', subtitle:'Find structure without labels', color:'aqua', symbol:'◌', lessons:[
    lesson('kmeans','K-Means clustering',15,'K-Means assigns points to the nearest centroid and updates centroids repeatedly. Scale features and compare several k values.','KMeans(n_clusters=3, random_state=42)','K in K-Means represents…',['Number of clusters','Number of features','Accuracy'],0,'K is the number of groups the algorithm will form.'),
    lesson('pca','Principal component analysis',17,'PCA rotates features into orthogonal components that capture maximum variance. It helps compression and visualisation.','PCA(n_components=2).fit_transform(X_scaled)','Should features usually be scaled before PCA?',['Yes','Never','Only text'],0,'PCA is variance-based, so scale strongly affects its result.'),
  ]},
  { id:'deep', number:'08', title:'Deep learning', subtitle:'Neural networks, tensors & CNNs', color:'navy', symbol:'◈', lessons:[
    lesson('neural-nets','Neural network basics',18,'Layers transform tensors using weights and nonlinear activations. Backpropagation computes gradients; an optimiser updates weights.','Dense(64, activation="relu")','What updates model weights?',['The optimiser','The CSV file','The test label'],0,'Optimisers such as Adam apply gradient-based updates.'),
    lesson('cnn','Convolutional networks',18,'CNN filters detect local visual patterns and share weights across image positions, making them efficient for spatial data.','Conv2D(32, kernel_size=3, activation="relu")','CNNs are especially suited to…',['Images','Random passwords','SQL tables only'],0,'Their local filters exploit spatial structure in images.'),
  ]},
  { id:'genai', number:'09', title:'NLP & GenAI', subtitle:'Embeddings, transformers and RAG', color:'lime', symbol:'✦', lessons:[
    lesson('embeddings','Embeddings',15,'Embeddings map meaning into vectors. Similar items lie near each other, enabling semantic search, recommendations and clustering.','similarity = cosine(query_vec, doc_vec)','What does high cosine similarity suggest?',['Similar direction/meaning','Different file size','Guaranteed truth'],0,'Cosine similarity compares vector direction, often reflecting semantic closeness.'),
    lesson('transformers','Transformers & LLMs',18,'Transformers use attention to combine relevant context. LLMs predict tokens and can be adapted through prompting, tools or fine-tuning.','prompt → tokens → model → next-token probabilities','What mechanism connects relevant context?',['Attention','K-Means','One-hot labels only'],0,'Attention weights contextual relationships between tokens.'),
    lesson('rag','RAG & agents',18,'RAG retrieves relevant sources before generation. Agents combine models with tools and control logic to complete multi-step tasks.','query → retrieve → ground prompt → generate','What is RAG mainly designed to add?',['Relevant external context','More screen brightness','A test split'],0,'Retrieval grounds the generation in selected source material.'),
  ]},
  { id:'mlops', number:'10', title:'MLOps', subtitle:'Ship, observe and improve models', color:'grey', symbol:'⬡', lessons:[
    lesson('serve-app','APIs & apps',15,'FastAPI exposes prediction endpoints; Streamlit quickly creates interactive data apps. Validate inputs and version model artefacts.','@app.post("/predict")','What should an API validate?',['Incoming inputs','Only button colour','Nothing'],0,'Validation prevents malformed or unsafe input reaching the model.'),
    lesson('containers-ci','Docker & CI',17,'Docker packages an app with its runtime. CI runs tests and checks automatically when code changes.','docker build -t ml-api .','What does a container improve?',['Environment consistency','Model accuracy automatically','Label quality'],0,'The same packaged environment can run locally and in deployment.'),
    lesson('tracking-deploy','Tracking & monitoring',17,'MLflow records experiments. Production monitoring watches latency, failures, data drift and model quality over time.','mlflow.log_metric("rmse", rmse)','Why monitor after deployment?',['Real data can change','Training never finishes','To hide errors'],0,'Data and behaviour drift can reduce performance after launch.'),
  ]},
];
export const lessonIds = modules.flatMap((module) => module.lessons.map((item) => item.id));
