export type Lesson = {
  id: string; title: string; minutes: number; explanation: string; example: string;
  exercise: { question: string; choices: string[]; answer: number; feedback: string };
  interview: { question: string; answer: string };
};
export type Module = { id:string; number:string; title:string; subtitle:string; color:string; symbol:string; lessons:Lesson[] };
const lesson = (id:string,title:string,minutes:number,explanation:string,example:string,question:string,choices:string[],answer:number,feedback:string):Lesson => ({id,title,minutes,explanation,example,exercise:{question,choices,answer,feedback},interview:{question,answer:feedback}});

export const modules: Module[] = [
  { id:'data', number:'01', title:'Data foundations', subtitle:'NumPy, Pandas & visualisation', color:'sun', symbol:'▦', lessons:[
    lesson('numpy-arrays','NumPy arrays',12,'Arrays store values of one type and make numerical operations fast. Shape describes their dimensions; indexing selects individual values or slices.','x = np.array([2, 4, 6])\nx.mean()  # 4.0','Which expression selects the first item in x?',['x[0]','x[1]','x.first()'],0,'Python uses zero-based indexing, so the first position is 0.'),
    lesson('pandas-frames','Pandas DataFrames',15,'A DataFrame is a labelled table. Columns are features and rows are observations. Use head(), info() and describe() to understand a new dataset.','df = pd.read_csv("sales.csv")\ndf.head()','Which method reveals column types and missing counts?',['df.plot()','df.info()','df.sample()'],1,'info() summarizes columns, data types and non-null counts.'),
    lesson('eda-workflow','Exploratory data analysis',18,'EDA is a structured investigation of data quality, distributions, relationships and unusual cases before modelling. Start with questions, use summaries and plots, then record findings that affect preprocessing or model choice.','df.info()\ndf.describe(include="all")\nsns.pairplot(df, hue="churn")','What is the main goal of EDA?',['Understand the data before modelling','Maximise test accuracy directly','Deploy an API'],0,'EDA helps you discover quality issues, patterns and modelling risks before training.'),
    lesson('clean-data','Cleaning data',14,'Clean data before modelling: remove duplicates, correct types and decide how to handle missing values. Never hide these decisions.','df["age"] = df["age"].fillna(df["age"].median())','What is a sensible fill value for skewed numeric data?',['The median','A random word','Always zero'],0,'The median is robust to unusually large or small values.'),
    lesson('categoricals','Categorical variables',13,'Models need numbers. One-hot encoding creates a binary column for each unordered category; ordinal encoding is for ordered categories.','pd.get_dummies(df, columns=["city"])','Which encoding fits red, green and blue?',['One-hot encoding','Date encoding','Min-max scaling'],0,'Colours have no natural order, so one-hot encoding is appropriate.'),
    lesson('missing-values','Missing values',14,'Missing values can be removed, filled with a statistic, or modelled explicitly. Choose a method based on why the value is missing and fit imputers using training data only.','SimpleImputer(strategy="median").fit_transform(X_train)','Why fit an imputer only on training data?',['To avoid leakage','To make more nulls','To sort the rows'],0,'Using validation or test statistics leaks information into the model.'),
    lesson('matplotlib','Matplotlib essentials',14,'Matplotlib is Python’s foundational plotting library. A figure contains one or more axes; labels, titles and scales make the chart interpretable.','fig, ax = plt.subplots()\nax.plot(x, y)\nax.set(title="Trend", xlabel="Time")','What object normally contains the plotted data?',['Axes','CSV','Estimator'],0,'The Axes object owns plot elements, labels and scales.'),
    lesson('seaborn','Seaborn concepts',13,'Seaborn builds statistical charts on Matplotlib and works naturally with tidy DataFrames. Use it to compare distributions, categories and relationships.','sns.scatterplot(data=df, x="age", y="income", hue="segment")','What does hue usually represent?',['A grouping variable','File size','Missing rows'],0,'hue maps a data variable to colour so groups can be compared.'),
    lesson('features-target','Features and target',12,'Features are the inputs a model uses; the target is what it learns to predict. Separating them clearly prevents accidental target leakage.','X = df.drop(columns="price")\ny = df["price"]','Which variable conventionally stores the target?',['y','X','df.columns'],0,'In scikit-learn examples, X holds features and y holds the target.'),
  ]},
  { id:'stats', number:'02', title:'Statistics for ML', subtitle:'Probability, distributions & testing', color:'mint', symbol:'⌁', lessons:[
    lesson('center-spread','Centre and spread',14,'Mean and median describe centre. Variance and standard deviation describe spread. Compare both when distributions contain outliers.','values.mean()\nvalues.std()','Which measure is least affected by one extreme outlier?',['Mean','Median','Variance'],1,'The median depends on rank, not the magnitude of the extreme value.'),
    lesson('distributions','Distributions',16,'A distribution describes possible values and their frequency. Normal distributions are symmetric; real data may be skewed or multi-modal.','sns.histplot(df["income"], kde=True)','A long right tail indicates what?',['Right skew','Perfect normality','No variation'],0,'A few high values stretch the distribution to the right.'),
    lesson('correlation','Correlation',12,'Correlation measures linear association, not causation. Values near +1 or -1 indicate strong linear relationships; near 0 means weak linear association.','df.corr(numeric_only=True)','If r = -0.9, the variables have…',['A strong negative relationship','No relationship','A strong positive relationship'],0,'As one variable rises, the other tends to fall strongly.'),
    lesson('hypothesis','Hypothesis testing',18,'A hypothesis test asks whether evidence is inconsistent with a null hypothesis. A p-value is not the probability that the null is true.','stats.ttest_ind(group_a, group_b)','With α=.05 and p=.02, what is the usual decision?',['Reject the null','Prove the null','Increase p manually'],0,'Because p is below α, the data is considered inconsistent with the null.'),
    lesson('probability','Probability foundations',16,'Probability measures uncertainty from 0 to 1. Conditional probability updates the chance of an event when new information is known.','P(A_given_B) = P(A_and_B) / P(B)','A probability of 0.8 means…',['The event is expected about 80% of repeated trials','The event is guaranteed','The event is impossible'],0,'Probability describes long-run uncertainty, not certainty for one observation.'),
    lesson('outliers','Outliers',14,'Outliers are unusually distant observations. Investigate them before removal: they may be errors, rare valid cases or the most valuable signal.','q1, q3 = s.quantile([.25, .75])\niqr = q3 - q1','Should every outlier be deleted?',['No, investigate first','Yes, always','Only in classification'],0,'Outliers can be valid and informative, so context must guide treatment.'),
  ]},
  { id:'core', number:'03', title:'Core machine learning', subtitle:'Train, validate and generalise', color:'blue', symbol:'⌘', lessons:[
    lesson('problem-types','Regression vs classification',11,'Regression predicts a continuous value. Classification predicts a category or class probability.','price → regression\nspam/not spam → classification','Predicting house price is…',['Regression','Classification','Clustering'],0,'Price is a continuous numeric target.'),
    lesson('train-test','Train/test split',13,'Fit the model on training data and reserve test data for a final unbiased check. Split before learning preprocessing parameters.','train_test_split(X, y, test_size=.2, random_state=42)','Why keep a test set?',['Estimate performance on unseen data','Make training slower','Store missing values'],0,'The test set simulates future examples the model did not train on.'),
    lesson('fit-balance','Overfitting & underfitting',14,'An underfit model is too simple for the pattern. An overfit model memorises training noise and performs poorly on new data.','high train score + low test score → overfit','Which pattern suggests overfitting?',['95% train, 62% test','60% train, 60% test','95% train, 94% test'],0,'The large generalisation gap is the key warning sign.'),
    lesson('cross-validation','Cross-validation',16,'K-fold cross-validation rotates the validation fold, producing a more stable performance estimate and revealing variability.','cross_val_score(model, X, y, cv=5)','In 5-fold CV, how many validation rounds run?',['1','5','10'],1,'Every fold acts as validation data once.'),
  ]},
  { id:'algorithms', number:'04', title:'ML algorithms', subtitle:'From linear models to boosting', color:'rose', symbol:'⤴', lessons:[
    lesson('linear-regression','Linear regression',17,'Linear regression predicts a continuous target using a weighted sum of features. Its coefficients describe direction and size on the model scale, while residuals reveal where its assumptions break down.','model = LinearRegression()\nmodel.fit(X_train, y_train)\npred = model.predict(X_test)','Which target is appropriate for linear regression?',['House price','Spam or not spam','Customer segment name'],0,'Linear regression is designed for continuous numeric targets such as price.'),
    lesson('linear-logistic','Linear & logistic regression',17,'Linear regression predicts numbers with a weighted sum. Logistic regression maps a weighted sum to a class probability.','LogisticRegression().fit(X_train, y_train)','Which model predicts a yes/no outcome?',['Linear regression','Logistic regression','PCA'],1,'Logistic regression is a classification algorithm despite its name.'),
    lesson('trees-forests','Trees & random forests',18,'Decision trees make readable splits. Random forests average many varied trees, reducing variance and usually improving generalisation.','RandomForestClassifier(n_estimators=200)','Why use many trees?',['Reduce variance','Remove the target','Guarantee perfection'],0,'Averaging decorrelated trees creates a more stable model.'),
    lesson('knn-svm','KNN & SVM',18,'KNN predicts from nearby training examples. SVM finds a boundary with maximum margin and benefits strongly from scaled features.','make_pipeline(StandardScaler(), SVC())','Which step is especially important for SVM?',['Feature scaling','Alphabetical sorting','Dropping all labels'],0,'Large-scale features can otherwise dominate distances and margins.'),
    lesson('boosting','Gradient boosting',18,'Boosting builds weak learners sequentially, with each new tree correcting previous errors. Learning rate and tree count work together.','XGBClassifier(n_estimators=300, learning_rate=.05)','Boosting trees are built…',['Sequentially','As one giant tree','Without errors'],0,'Each learner focuses on what the current ensemble gets wrong.'),
    lesson('decision-tree','Decision trees',17,'A decision tree recursively splits features to make groups purer. Depth controls complexity and readable rules make trees useful baselines.','DecisionTreeClassifier(max_depth=4, random_state=42)','What usually happens when depth is unrestricted?',['Overfitting risk rises','All features disappear','The task becomes regression'],0,'Very deep trees can memorise small details in the training set.'),
    lesson('random-forest','Random forests',17,'A random forest trains many trees on bootstrapped samples and random feature subsets, then averages their predictions.','RandomForestClassifier(n_estimators=300, max_features="sqrt")','Why randomise features across trees?',['Decorrelate the trees','Delete the target','Avoid all tuning'],0,'Less-correlated trees produce a stronger averaged ensemble.'),
    lesson('knn','K-nearest neighbours',15,'KNN predicts from the labels or values of nearby examples. Distance scale and the choice of k strongly affect the result.','make_pipeline(StandardScaler(), KNeighborsClassifier(n_neighbors=5))','Why scale before KNN?',['Distance depends on feature scale','KNN requires images','Scaling creates labels'],0,'A large-scale feature can otherwise dominate the distance calculation.'),
    lesson('svm','Support vector machines',17,'An SVM searches for a maximum-margin boundary. Kernels let it model nonlinear boundaries, while C controls the penalty for mistakes.','make_pipeline(StandardScaler(), SVC(kernel="rbf", C=1))','What does the margin describe?',['Distance from the boundary to closest points','Number of rows','Target average'],0,'Support vectors nearest the decision boundary determine the margin.'),
    lesson('xgboost','XGBoost',18,'XGBoost is an efficient regularised gradient-boosting implementation. Control learning rate, depth and number of trees together.','XGBClassifier(max_depth=4, learning_rate=.05, n_estimators=400)','What is a safer tuning pattern?',['Smaller learning rate with more trees','Maximum depth everywhere','Use the test set repeatedly'],0,'A lower learning rate with enough learners often improves generalisation.'),
    lesson('model-comparison','Compare multiple ML models',19,'A fair comparison uses the same split, preprocessing and primary metric for every candidate. Cross-validation gives a more stable estimate, while a final untouched test set confirms the selected model.','for name, model in models.items():\n    scores[name] = cross_val_score(model, X, y, cv=5).mean()','What makes a model comparison fair?',['The same validation design and metric','Different test sets for each model','Choosing the largest model'],0,'Models must be evaluated under the same preprocessing, folds and metric.'),
  ]},
  { id:'evaluation', number:'05', title:'Model evaluation', subtitle:'Use the metric that matches the goal', color:'violet', symbol:'◎', lessons:[
    lesson('regression-metrics','Regression metrics',15,'MAE is easy to interpret, MSE/RMSE penalise large misses, and R² compares performance with predicting the mean.','mean_absolute_error(y_test, pred)','Which metric stays in the target unit and is robust?',['MAE','MSE','Accuracy'],0,'MAE is the average absolute error in the original target unit.'),
    lesson('classification-metrics','Precision, recall & F1',16,'Precision asks how many positive predictions were correct. Recall asks how many real positives were found. F1 balances both.','classification_report(y_test, pred)','For disease screening, which often matters most?',['Recall','R²','MAE'],0,'High recall reduces the number of missed positive cases.'),
    lesson('roc-confusion','Confusion matrix & ROC-AUC',16,'A confusion matrix counts prediction outcomes. ROC-AUC measures ranking quality across classification thresholds.','ConfusionMatrixDisplay.from_predictions(y, pred)','A false positive means…',['Predicted yes, actually no','Predicted no, actually yes','Predicted correctly'],0,'The model raised a positive signal for a negative case.'),
  ]},
  { id:'pipelines', number:'06', title:'Features & pipelines', subtitle:'Reliable preprocessing and tuning', color:'orange', symbol:'⇄', lessons:[
    lesson('scaling-encoding','Scaling & encoding',16,'Scale numeric features and encode categorical ones. Learn every transformation only from training data to prevent leakage.','ColumnTransformer([("num", StandardScaler(), nums)])','When should a scaler learn mean and std?',['Training data only','Full dataset before splitting','Test data only'],0,'Using test statistics leaks information into training.'),
    lesson('pipeline','ColumnTransformer & Pipeline',17,'A Pipeline chains preprocessing and modelling so the same fitted steps run during validation, testing and prediction.','Pipeline([("prep", prep), ("model", model)])','What key problem does a pipeline reduce?',['Data leakage','Disk space','Class names'],0,'Pipelines keep preprocessing inside each training fold.'),
    lesson('tuning','Hyperparameter tuning',18,'Grid or random search tests configurations using cross-validation. Tune on validation folds, then evaluate once on untouched test data.','RandomizedSearchCV(pipe, params, cv=5)','What data should choose hyperparameters?',['Validation folds','Final test set','Future production labels'],0,'The final test set must remain an unbiased last check.'),
    lesson('feature-selection','Feature selection',15,'Feature selection removes unhelpful or redundant inputs. Use domain knowledge, univariate tests, regularisation or model-based importance inside validation.','SelectKBest(k=10)','Where should selection be fitted?',['Inside the training pipeline','On the full dataset','Only on test data'],0,'Selection must happen inside validation folds to prevent leakage.'),
    lesson('model-persistence','Save and load a trained model',14,'Persist the complete fitted pipeline—not only the estimator—so production applies identical preprocessing. Record the library version, feature schema and training metadata with the artefact.','import joblib\njoblib.dump(pipeline, "model.joblib")\nmodel = joblib.load("model.joblib")','What should normally be saved for deployment?',['The complete fitted pipeline','Only the predictions','The test labels'],0,'Saving the fitted pipeline keeps preprocessing and prediction logic together.'),
  ]},
  { id:'unsupervised', number:'07', title:'Unsupervised ML', subtitle:'Find structure without labels', color:'aqua', symbol:'◌', lessons:[
    lesson('kmeans','K-Means clustering',15,'K-Means assigns points to the nearest centroid and updates centroids repeatedly. Scale features and compare several k values.','KMeans(n_clusters=3, random_state=42)','K in K-Means represents…',['Number of clusters','Number of features','Accuracy'],0,'K is the number of groups the algorithm will form.'),
    lesson('pca','Principal component analysis',17,'PCA rotates features into orthogonal components that capture maximum variance. It helps compression and visualisation.','PCA(n_components=2).fit_transform(X_scaled)','Should features usually be scaled before PCA?',['Yes','Never','Only text'],0,'PCA is variance-based, so scale strongly affects its result.'),
    lesson('cluster-evaluation','Evaluating clusters',14,'Without labels, inspect cohesion, separation and stability. Silhouette score is useful, but domain meaning matters more than one metric.','silhouette_score(X_scaled, labels)','What does a higher silhouette score suggest?',['Better separated clusters','More missing values','Guaranteed useful segments'],0,'It suggests tighter, better-separated groups but does not prove business value.'),
  ]},
  { id:'deep', number:'08', title:'Deep learning', subtitle:'Neural networks, tensors & CNNs', color:'navy', symbol:'◈', lessons:[
    lesson('neural-nets','Neural network basics',18,'Layers transform tensors using weights and nonlinear activations. Backpropagation computes gradients; an optimiser updates weights.','Dense(64, activation="relu")','What updates model weights?',['The optimiser','The CSV file','The test label'],0,'Optimisers such as Adam apply gradient-based updates.'),
    lesson('cnn','Convolutional networks',18,'CNN filters detect local visual patterns and share weights across image positions, making them efficient for spatial data.','Conv2D(32, kernel_size=3, activation="relu")','CNNs are especially suited to…',['Images','Random passwords','SQL tables only'],0,'Their local filters exploit spatial structure in images.'),
    lesson('tensorflow','TensorFlow and Keras',17,'TensorFlow provides tensor operations and deployment tools; Keras supplies a high-level API for defining and training neural networks.','model = keras.Sequential([keras.layers.Dense(64, activation="relu")])','What does model.fit do?',['Runs the training loop','Creates a CSV','Deploys automatically'],0,'fit iterates over batches, computes gradients and updates weights.'),
    lesson('pytorch','PyTorch basics',17,'PyTorch uses eager tensors, modules and autograd. A typical loop clears gradients, computes loss, backpropagates and steps the optimiser.','optimizer.zero_grad()\nloss.backward()\noptimizer.step()','Why clear gradients each step?',['Gradients accumulate by default','It deletes the model','It normalises labels'],0,'PyTorch accumulates gradients unless they are explicitly reset.'),
  ]},
  { id:'genai', number:'09', title:'NLP & GenAI', subtitle:'Embeddings, transformers and RAG', color:'lime', symbol:'✦', lessons:[
    lesson('embeddings','Embeddings',15,'Embeddings map meaning into vectors. Similar items lie near each other, enabling semantic search, recommendations and clustering.','similarity = cosine(query_vec, doc_vec)','What does high cosine similarity suggest?',['Similar direction/meaning','Different file size','Guaranteed truth'],0,'Cosine similarity compares vector direction, often reflecting semantic closeness.'),
    lesson('transformers','Transformers & LLMs',18,'Transformers use attention to combine relevant context. LLMs predict tokens and can be adapted through prompting, tools or fine-tuning.','prompt → tokens → model → next-token probabilities','What mechanism connects relevant context?',['Attention','K-Means','One-hot labels only'],0,'Attention weights contextual relationships between tokens.'),
    lesson('rag','RAG & agents',18,'RAG retrieves relevant sources before generation. Agents combine models with tools and control logic to complete multi-step tasks.','query → retrieve → ground prompt → generate','What is RAG mainly designed to add?',['Relevant external context','More screen brightness','A test split'],0,'Retrieval grounds the generation in selected source material.'),
    lesson('hugging-face','Hugging Face',17,'Hugging Face provides model hubs, tokenizers, datasets and pipelines. Start with a pretrained model, then evaluate before considering fine-tuning.','pipeline("sentiment-analysis")("ML is exciting")','What is a pipeline?',['A convenient inference wrapper','A database table','A train/test split'],0,'Pipelines bundle preprocessing, model inference and output formatting.'),
    lesson('llm-apis','LLM APIs',16,'LLM APIs accept structured prompts and return generated output. Treat outputs as untrusted, validate tool inputs and control cost, latency and retries.','response = client.responses.create(model="...", input=prompt)','What should production code always handle?',['Errors, limits and validation','Only font colour','No failures'],0,'Network calls and model outputs require defensive validation and retry logic.'),
    lesson('vector-databases','Vector databases',17,'Vector databases index embeddings for approximate nearest-neighbour search. Store source metadata so retrieved chunks remain traceable.','results = index.query(vector=query_embedding, top_k=5)','Why store metadata with vectors?',['Trace results back to sources','Increase monitor brightness','Replace embeddings'],0,'Metadata enables filtering, citations and source inspection.'),
    lesson('agents','AI agents',18,'An agent combines a model, instructions, tools and a control loop. Keep permissions narrow and add stopping conditions, logging and human approval.','while not done:\n    action = model.decide(state)\n    state = tool(action)','What limits runaway behaviour?',['Bounded tools and stopping conditions','Longer prompts only','Removing logs'],0,'Explicit boundaries and termination rules make agent behaviour safer.'),
  ]},
  { id:'mlops', number:'10', title:'MLOps', subtitle:'Ship, observe and improve models', color:'grey', symbol:'⬡', lessons:[
    lesson('serve-app','APIs & apps',15,'FastAPI exposes prediction endpoints; Streamlit quickly creates interactive data apps. Validate inputs and version model artefacts.','@app.post("/predict")','What should an API validate?',['Incoming inputs','Only button colour','Nothing'],0,'Validation prevents malformed or unsafe input reaching the model.'),
    lesson('containers-ci','Docker & CI',17,'Docker packages an app with its runtime. CI runs tests and checks automatically when code changes.','docker build -t ml-api .','What does a container improve?',['Environment consistency','Model accuracy automatically','Label quality'],0,'The same packaged environment can run locally and in deployment.'),
    lesson('docker-hands-on','Docker hands-on',18,'A Dockerfile defines a repeatable image: choose a small base image, install pinned dependencies, copy the app, expose its port and start one production command. Use a .dockerignore to keep secrets and unnecessary files out.','docker build -t churn-api .\ndocker run -p 8000:8000 churn-api','What does docker run -p 8000:8000 do?',['Maps the container port to the host','Retrains the model','Publishes to GitHub'],0,'The port mapping makes the container service reachable from the host machine.'),
    lesson('tracking-deploy','Tracking & monitoring',17,'MLflow records experiments. Production monitoring watches latency, failures, data drift and model quality over time.','mlflow.log_metric("rmse", rmse)','Why monitor after deployment?',['Real data can change','Training never finishes','To hide errors'],0,'Data and behaviour drift can reduce performance after launch.'),
    lesson('fastapi','FastAPI model APIs',16,'FastAPI creates typed HTTP endpoints. Load the model once, validate request schemas and return predictable response shapes.','@app.post("/predict")\ndef predict(row: Features): return {"prediction": model.predict([row.values])[0]}','Why use a request schema?',['Validate incoming data','Increase model depth','Create training labels'],0,'Typed schemas reject malformed requests before inference.'),
    lesson('streamlit','Streamlit apps',14,'Streamlit turns Python scripts into interactive data apps. Cache expensive resources and separate interface code from model logic.','value = st.number_input("Age")\nst.write(model.predict([[value]]))','What should be cached?',['Expensive stable resources','Every user input forever','Passwords'],0,'Models and shared data can be cached to avoid repeated loading.'),
    lesson('mlflow','MLflow experiments',15,'MLflow records parameters, metrics and model artefacts so experiments can be compared and reproduced.','with mlflow.start_run():\n    mlflow.log_params(params)\n    mlflow.log_metric("rmse", rmse)','Why log parameters with metrics?',['Reproduce the winning run','Make files larger','Avoid validation'],0,'A metric is useful only when you know which configuration produced it.'),
    lesson('github-actions','GitHub Actions CI',16,'A CI workflow automatically installs dependencies, runs tests and checks builds on pushes or pull requests.','- run: pip install -r requirements.txt\n- run: pytest','What should fail a deployment pipeline?',['Broken tests','A useful comment','A smaller image'],0,'Automated checks stop known-bad changes from shipping.'),
    lesson('cloud-deployment','Cloud deployment',17,'Cloud deployment combines an application runtime, environment variables, observability and a repeatable release process. Never bake secrets into images.','docker run -e MODEL_PATH=/models/model.pkl ml-api','Where should production secrets live?',['Managed environment secrets','Source control','Public JavaScript'],0,'Use the platform’s secret store or protected environment variables.'),
  ]},
];
export const lessonIds = modules.flatMap((module) => module.lessons.map((item) => item.id));

export const appliedStages = [
  { number:'01', title:'Pandas + EDA', lessonId:'eda-workflow', outcome:'Inspect, clean and explain a real dataset' },
  { number:'02', title:'Statistics', lessonId:'center-spread', outcome:'Measure patterns and test assumptions' },
  { number:'03', title:'Linear Regression', lessonId:'linear-regression', outcome:'Build your first regression baseline' },
  { number:'04', title:'Data preprocessing', lessonId:'scaling-encoding', outcome:'Create leakage-safe transformations' },
  { number:'05', title:'Random Forest', lessonId:'random-forest', outcome:'Train a strong ensemble model' },
  { number:'06', title:'Compare ML models', lessonId:'model-comparison', outcome:'Select a winner with fair validation' },
  { number:'07', title:'Hyperparameter tuning', lessonId:'tuning', outcome:'Improve the model systematically' },
  { number:'08', title:'Save trained model', lessonId:'model-persistence', outcome:'Export a production-ready pipeline' },
  { number:'09', title:'FastAPI prediction API', lessonId:'fastapi', outcome:'Serve predictions through HTTP' },
  { number:'10', title:'Streamlit dashboard', lessonId:'streamlit', outcome:'Build an interactive model interface' },
  { number:'11', title:'Docker', lessonId:'docker-hands-on', outcome:'Package the complete application' },
  { number:'12', title:'GitHub Actions / MLOps', lessonId:'github-actions', outcome:'Test and ship with automation' },
];
