'use client';
import { useEffect, useMemo, useState } from 'react';
import { modules, type Lesson, type Module } from './curriculum';

export default function LearningApp({ email }: { email: string }) {
  const [completed,setCompleted]=useState<Set<string>>(new Set()); const [selected,setSelected]=useState<{lesson:Lesson;module:Module}|null>(null); const [answer,setAnswer]=useState<number|null>(null); const [filter,setFilter]=useState('all'); const [saving,setSaving]=useState(false);
  const total=modules.reduce((sum,item)=>sum+item.lessons.length,0);
  useEffect(()=>{ fetch('/api/progress').then(r=>{if(r.status===401){window.location.href='/login';return {completed:[]};}return r.ok?r.json():{completed:[]};}).then(data=>setCompleted(new Set(data.completed??[]))).catch(()=>undefined); },[]);
  const percent=Math.round((completed.size/total)*100); const visible=useMemo(()=>filter==='all'?modules:modules.filter(item=>item.id===filter),[filter]);
  async function toggleLesson(id:string){ const nextState=!completed.has(id); setSaving(true); const optimistic=new Set(completed); nextState?optimistic.add(id):optimistic.delete(id); setCompleted(optimistic); const response=await fetch('/api/progress',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lessonId:id,completed:nextState})}); if(!response.ok)setCompleted(completed); setSaving(false); }
  function openLesson(module:Module,lesson:Lesson){setSelected({module,lesson});setAnswer(null);} const nextLesson=modules.flatMap(module=>module.lessons.map(lesson=>({module,lesson}))).find(({lesson})=>!completed.has(lesson.id));
  return <main>
    <header className="topbar"><a className="brand" href="#top">learn<span>flow</span>.</a><nav aria-label="Primary navigation"><a className="active" href="#path">Path</a><a href="/learn">Learning</a><a href="/tasks">Tasks</a></nav><div className="signed-account"><div><strong>{email.split('@')[0]}</strong><small>{email}</small></div><form action="/auth/signout" method="post"><button type="submit">Sign out</button></form></div></header>
    <section className="hero" id="top"><div className="eyebrow"><span/>Your machine learning path</div><h1>Learn ML from the<br/><em>ground up.</em></h1><p>Short lessons. Real exercises. A clear path from your first DataFrame to deployed AI.</p><div className="hero-actions"><button className="primary-button" onClick={()=>{window.location.href=nextLesson?`/learn?lesson=${nextLesson.lesson.id}`:'/tasks'}}>{completed.size?'Continue learning':'Start learning'} <span>→</span></button><div className="streak"><strong>{completed.size}</strong><span>lessons<br/>complete</span></div></div></section>
    <section className="dashboard" id="path"><div className="section-heading"><div><span className="kicker">Curriculum</span><h2>Your learning path</h2></div><div className="overall" id="progress"><span>Overall progress</span><strong>{percent}%</strong><div><i style={{width:`${percent}%`}}/></div><small>{completed.size} of {total} lessons</small></div></div><div className="filter-row"><button className={filter==='all'?'selected':''} onClick={()=>setFilter('all')}>All chapters</button>{modules.slice(0,5).map(item=><button key={item.id} className={filter===item.id?'selected':''} onClick={()=>setFilter(item.id)}>{item.number}</button>)}</div>
      <div className="track-grid" id="practice">{visible.map(module=>{const count=module.lessons.filter(item=>completed.has(item.id)).length;const modulePercent=Math.round(count/module.lessons.length*100);const firstOpen=module.lessons.find(item=>!completed.has(item.id))??module.lessons[0];return <article className={`track-card ${module.color}`} key={module.id}><div className="track-top"><span className="track-number">{module.number}</span><span className="lesson-count">{module.lessons.length} lessons</span></div><div className="track-art" aria-hidden="true"><span>{module.symbol}</span></div><h3>{module.title}</h3><p>{module.subtitle}</p><ul className="lesson-list">{module.lessons.map(item=><li key={item.id}><button onClick={()=>openLesson(module,item)}><span className={completed.has(item.id)?'check done':'check'}>{completed.has(item.id)?'✓':''}</span><span>{item.title}<small>{item.minutes} min · exercise</small></span><b>→</b></button></li>)}</ul><div className="card-progress"><span><i style={{width:`${modulePercent}%`}}/></span><small>{count?`${modulePercent}% complete`:'Not started'}</small></div><button className="chapter-action" onClick={()=>openLesson(module,firstOpen)}>{count?'Continue chapter':'Start chapter'} <span>↗</span></button></article>})}</div>
    </section>
    <section className="method"><span className="kicker">How it works</span><h2>Small steps. Real momentum.</h2><div><article><b>01</b><h3>Learn</h3><p>Read one focused concept with a practical code example.</p></article><article><b>02</b><h3>Practice</h3><p>Answer a quick check to lock in what you just learned.</p></article><article><b>03</b><h3>Track</h3><p>Mark it complete and pick up exactly where you left off.</p></article></div></section>
    <footer><a className="brand" href="#top">learn<span>flow</span>.</a><p>Traditional ML first. Generative AI when the foundations are strong.</p><a href="#top">Back to top ↑</a></footer>
    {selected&&<div className="modal-backdrop" role="presentation" onMouseDown={event=>event.currentTarget===event.target&&setSelected(null)}><section className="lesson-modal" role="dialog" aria-modal="true" aria-labelledby="lesson-title"><header><div><span>{selected.module.number} / {selected.module.title}</span><h2 id="lesson-title">{selected.lesson.title}</h2></div><button onClick={()=>setSelected(null)} aria-label="Close lesson">×</button></header><div className="lesson-body"><div className="lesson-meta"><span>{selected.lesson.minutes} min</span><span>Beginner friendly</span><span>1 exercise</span></div><h3>The idea</h3><p>{selected.lesson.explanation}</p><h3>Try the pattern</h3><pre><code>{selected.lesson.example}</code></pre><div className="exercise"><span className="kicker">Quick check</span><h3>{selected.lesson.exercise.question}</h3><div className="choices">{selected.lesson.exercise.choices.map((choice,index)=><button key={choice} className={answer===index?(index===selected.lesson.exercise.answer?'correct':'wrong'):''} onClick={()=>setAnswer(index)}><span>{String.fromCharCode(65+index)}</span>{choice}</button>)}</div>{answer!==null&&<p className={answer===selected.lesson.exercise.answer?'feedback good':'feedback'}>{answer===selected.lesson.exercise.answer?'Correct — ':'Not quite — '}{selected.lesson.exercise.feedback}</p>}</div></div><footer><button className={completed.has(selected.lesson.id)?'complete-button completed':'complete-button'} disabled={saving} onClick={()=>toggleLesson(selected.lesson.id)}>{completed.has(selected.lesson.id)?'✓ Completed':'Mark lesson complete'}</button></footer></section></div>}
  </main>;
}
